name: jbook
channels:
  - conda-forge
dependencies:
  - python=3.13
  - mystmd
  - jupytext
  - jupyter-book
  - myst-parser
  - pre-commit
  - texlive-core
  - latexmk
  - pip
  - pip:
      - cookiecutter
    #   - sphinx-proof
